vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        card:
            uri_prefix: /images/card
            upload_destination: '%kernel.project_dir%/public/images/card'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


        partner:
            uri_prefix: /images/partner
            upload_destination: '%kernel.project_dir%/public/images/partner'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer