vich_uploader:
    db_driver: orm

    mappings:
        card_images:
            uri_prefix: /images/card
            upload_destination: '%kernel.project_dir%/public/images/card'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
